name: Deploy
on:
  workflow_run:
    workflows: [Build]
    types: [completed]
    branches: [feature/build-deploy-workflow]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Deploy complete"